# JavaChatX Configuration

# Application settings
application:
  name: JavaChatX
  version: 1.0.0
  description: AI Agent Development Framework

# Chat engine settings
chat:
  defaultEngine: simple
  sessionTimeout: 3600000 # 1 hour in milliseconds

# Context management settings
context:
  defaultManager: simple
  persistence: false # Whether to persist context data

# Plugin settings
plugins:
  directory: plugins
  autoLoad: true

# Logging configuration
logging:
  level: INFO
  file: logs/javachatx.log
  maxFileSize: 10MB
  maxBackupFiles: 5

# API settings
api:
  timeout: 30000 # 30 seconds in milliseconds
  retryAttempts: 3
  retryDelay: 1000 # 1 second in milliseconds
