name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Extract tag name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

      - name: Upload JAR Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/javachatx-${{ env.TAG_NAME }}.jar
          asset_name: javachatx-${{ env.TAG_NAME }}.jar
          asset_content_type: application/java-archive

  publish-maven-central:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Maven Central
        run: echo "Publishing to Maven Central - Future Implementation"
        # This is a placeholder for future Maven Central publishing
        # Implementation would require:
        # - Setting up Sonatype OSSRH account
        # - Configuring GPG signing
        # - Adding Maven publish plugin to pom.xml
        # - Setting up secrets in GitHub
